name: auto-pr-tag-release-action
description: "Automatically create PRs and tags for Telepresence releases"
inputs:
  gh_auto_release_token:
    description: "The token to use to authenticate with GitHub"
    required: true
  gh_auto_release_email:
    description: "The email to use to authenticate with GitHub"
    required: true
  gh_auto_release_user:
    description: "The user to use to authenticate with GitHub"
    required: true
  telepresence_version:
    description: "The current release of Telepresence in the form of vX.Y.Z[-rc.N]"
    required: true
  repository:
    description: "The repository to upgrade"
    required: true
  commands:
    description: "The commands to run"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout other repo
      uses: actions/checkout@v3
      with:
        path: remote_repo
        repository: ${{ inputs.repository }}
        token: ${{ inputs.GH_AUTO_RELEASE_TOKEN }}
        persist-credentials: false

    - name: Setup Git Config
      shell: bash
      run: |
        set -x

        git config --global user.email '${{ inputs.GH_AUTO_RELEASE_EMAIL }}'
        git config --global user.name '${{ inputs.GH_AUTO_RELEASE_USER }}'
        git config --global credential.helper 'store --file=/tmp/git-credentials'
        echo "https://x-access-token:${{ inputs.GH_AUTO_RELEASE_TOKEN }}@github.com" > /tmp/git-credentials

    - name: Set environment variables
      shell: bash
      run: |
        echo "RELEASE_BRANCH_NAME=release/$(echo ${{ inputs.telepresence_version }} | sed 's/^v//;s/-rc\.[0-9]*$//')" >> $GITHUB_ENV

    - uses: actions/setup-go@v3
      with:
        go-version: '~1.21.0'

    - name: Install GoMock
      shell: bash
      run: go install github.com/golang/mock/mockgen@v1.6.0

    - name: Execute command
      shell: bash
      working-directory: ./remote_repo
      env:
        TELEPRESENCE_VERSION: ${{ inputs.telepresence_version }}
      run: |
        ${{ inputs.commands }}

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5.0.1
      with:
        path: ./remote_repo
        title: "Telepresence ${{ env.RELEASE_BRANCH_NAME }}"
        branch: ${{ env.RELEASE_BRANCH_NAME }}
        token: ${{ inputs.GH_AUTO_RELEASE_TOKEN }}
        body: "New telepresence release"

    - name: Push tags
      shell: bash
      working-directory: ./remote_repo
      run: |
        git push origin {,rpc/}${{ inputs.telepresence_version }}
