name: slack-notification-workflow-error
description: "Send slack notification on workflow error"
inputs:
  slack_webhook_url:
    description: "The slack webhook url"
    required: true
runs:
  using: composite
  steps:
    - uses: technote-space/workflow-conclusion-action@v3
    - name: Notify Developers about Job Failure
      if: env.WORKFLOW_CONCLUSION == 'failure' || env.WORKFLOW_CONCLUSION == 'cancelled'
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "⚠️ Telepresence Release Failed!"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Check the build details <${{ github.event.pull_request.html_url || github.event.head_commit.url }}|here>."
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Telepresence team, please investigate the issue."
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK